### PR TITLE
Fix current event through fire

### LINKED ISSUE #551: aasm.current_event incorrectly yields nil when calling aasm.fire!(:event)
Given the following code excerpt:

```
aasm column :state do

  state :unkown, initial: true
  state :matched

  event :match do
    transitions from: :unknown, to: matched, after: :matched_event
  end

  def matched_event
    puts aasm.current_event  # yields nil if triggered with aasm.fire!(:match)
  end

end

aasm.match!                # => Correct, aasm.current_event yields 'match!'
aasm.fire!(:match)         # => Incorrect, aasm.current_event yields nil
```

Would be nice to get this fixed, as my controllers are beginning to look a lot like hackery (i have 30+ transitions) and have had to resort to this less than elegant code...

```
def update
  ...
  if model.respond_to?("may_#{params[:event]}?') && model.send("may_#{params[:event]}?")
    model.send("#{params[:event]}!")
  end
  ...
end
```

### PR DESCRIPTION
**Pull request by DoubleJarvis**
Should fix #551. It already has a PR that should fix it, but it has duplicate logic, and its just lying there for a year, unmerged, and the issue is still present.

### CODE REVIEW

File: spec/unit/event_spec.rb [hunk 1]
```diff
@@ -294,6 +294,17 @@
     pe.wakeup!
     expect(pe.aasm.current_event).to eql :wakeup!
   end
+
+  describe "when calling events with fire/fire!" do
+    it "fire should populate aasm.current_event" do
+      pe.aasm.fire(:wakeup)
+      expect(pe.aasm.current_event).to eq :wakeup
```
Comment (anilmaurya) [inline spec/unit/event_spec.rb]: Can you add assertion for transition as well?

**Comment by DoubleJarvis** [comment]
Are the tests in cf75bdb satisfactory, or you mean something else by transition? @anilmaurya

**Comment by anilmaurya** [comment]
@DoubleJarvis Tests looks good 👍. Thank you for contributing.

Tests are failing on travis for some other reason. First I will fix travis build then I will merge your PR.
